### PR TITLE
Corrected wrong links in clickable map

### PR DESCRIPTION
**Pull request by irfanurrehman**
updated/corrected couple of links and removed some unused ones

### CODE REVIEW

**Comment by irfanurrehman** [comment]
following changes done
 - cell links to etcd; corrected
 - etcd links to runtime schema; corrected
 - garden-linux links to rep; corrected
 - many unused rep links; removed

and also included the fix of this issue
 https://github.com/cloudfoundry-incubator/diego-design-notes/issues/12

**Comment by onsi** [comment]
Thanks for this - am going to update the omnigraffle document and regenerate the clickable map - that way these fixes will not be ephemeral.

**Comment by onsi** [comment]
I've fixed the doc manually -- thanks for your help!

**Comment by irfanurrehman** [comment]
Thanks Onsi!
closing the request as these changes are no longer needed.

**Pull request closed without merging**
